### ISSUE TITLE
Conversion of YAML to JSON schema

### ISSUE THREAD

**Issue by abhi12ravi** [OpenEthicsAI/OEDP#1]

**Comment by OpenEthicsAI** [comment]
Hi, here's the general overview

- Convert https://github.com/OpenEthicsAI/OEDP/tree/main/API/models to JSON schema from YAML
- Follow the newest hierarchy described here https://openethics.ai/oedp/ (not yet in the YAML) to incorporate the idea that there could be multiple models supporting a product
- Follow the latest meta-schema is 2020-12 from https://json-schema.org/specification
- Provide descriptions of the schema elements within the schema, in collaboration with other team members

**Comment by abhi12ravi** [comment]
Hi @nikiluk @OpenEthicsAI I've sent in a PR towards the first task. If that's fine, I will work on the next three tasks. Looking forward to your feedback!

**Comment by nikiluk** [comment]
@abhi12ravi great progress. One more thing in addition to my inline comments in JSON files, I suggest we store the resulting schemas in the root folder to avoid confusion and maybe even discontinue YAML over time as JSON provides richer descriptive capabilities. Feel free to commit with the brand new structure e.g. `/schema/Open Ehics Data Passport.json`

**Comment by abhi12ravi** [comment]
> @abhi12ravi great progress. One more thing in addition to my inline comments in JSON files, I suggest we store the resulting schemas in the root folder to avoid confusion and maybe even discontinue YAML over time as JSON provides richer descriptive capabilities. Feel free to commit with the brand new structure e.g. `/schema/Open Ehics Data Passport.json`

@nikiluk Could we have a separate issue for this request? It's a bit confusing for me.

**Comment by nikiluk** [comment]
@abhi12ravi I've corrected the errors in https://github.com/OpenEthicsAI/OEDP/pull/11 and merged the edits into main
